# Generated by Django 4.0.5 on 2022-07-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodius', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Canceled', 'Canceled')], max_length=100, null=True),
        ),
    ]
