# Generated by Django 4.0.5 on 2022-07-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
